### Hi there, I'm Mark Vincent!👋 || สวัสดีคร๊าบ 🙏 ผมมาร์ควินเซ็นต์ครับ 👋

>  West Visayas State University<br>
  Bachelor of Science in Computer Science Major in Artificial Intelligence 🧙‍♂️<br>
  

### 🌱 I’m currently learning ...
![alt text](https://github.com/maakulit/maakulit/blob/main/tools1.png "Tools")

### 📫 How to reach me: ...
Twitter [![Twitter Follow](https://img.shields.io/twitter/follow/vnctmc?style=social)](https://twitter.com/vnctmc)
* [School Email](mailto:mvatinon@wvsu.edu.ph)
<!--
**maakulit/maakulit** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
